<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning/blob/main/32_classification_metrics_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [284]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,f1_score,recall_score
from sklearn.tree import DecisionTreeClassifier

In [285]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/MachineLearning/main/heart.csv")

In [286]:
df.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

In [287]:
X=df.drop("target",axis=1)
y=df.iloc[:,-1]

In [288]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [289]:
lr=LogisticRegression(C=0.1, max_iter=1000)
lr.fit(X_train,y_train)

LogisticRegression(C=0.1, max_iter=1000)

In [290]:
accuracy_score(y_test,lr.predict(X_test))

0.8852459016393442

In [291]:
dt=DecisionTreeClassifier()

In [292]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [293]:
accuracy_score(y_test,dt.predict(X_test))

0.8360655737704918

In [294]:
from pandas.core.frame import DataFrame
print("Decsion tree")
pd.DataFrame(confusion_matrix(y_test,dt.predict(X_test)),columns=list(range(0,2)))

Decsion tree

    0   1
0  26   3
1   7  25

In [295]:
from sklearn.metrics import classification_report
print(classification_report(y_test,dt.predict(X_test) ))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84        29
           1       0.89      0.78      0.83        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61

In [296]:
print("Logistic Consfusiobtree")
print(pd.DataFrame(confusion_matrix(y_test,lr.predict(X_test)),columns=list(range(0,2))))
print("-"*50)
print("Precision - ",precision_score(y_test,lr.predict(X_test)))
print("Recall - ",recall_score(y_test,lr.predict(X_test)))
print("F1 score - ",f1_score(y_test,lr.predict(X_test)))

Logistic Consfusiobtree
    0   1
0  25   4
1   3  29
--------------------------------------------------
Precision -  0.8787878787878788
Recall -  0.90625
F1 score -  0.8923076923076924

In [297]:
precision_score(y_test,lr.predict(X_test),average=None)
#always 2 ko late

array([0.89285714, 0.87878788])

In [298]:
recall_score(y_test,lr.predict(X_test),average=None)

array([0.86206897, 0.90625   ])

In [299]:
recall_score(y_test,lr.predict(X_test),average="macro")

0.8841594827586207

In [300]:
recall_score(y_test,lr.predict(X_test),average="weighted")

0.8852459016393442

**Multi Class**

In [301]:
from sklearn.datasets import load_iris

In [302]:
X1,y1=load_iris(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(X1,y1, test_size=0.2, random_state=42)

In [303]:
lr1=LogisticRegression()
lr1.fit(X_train,y_train)
print("Multi  tree")
pd.DataFrame(confusion_matrix(y_test,lr1.predict(X_test)),columns=list(range(0,3)))

Multi  tree

    0  1   2
0  10  0   0
1   0  9   0
2   0  0  11

In [304]:
accuracy_score(y_test,lr1.predict(X_test))

1.0

In [305]:
print("Precision - ",precision_score(y_test,lr1.predict(X_test), average='weighted'))
print("Recall - ",recall_score(y_test,lr1.predict(X_test), average='weighted'))
print("F1 score - ",f1_score(y_test,lr1.predict(X_test), average='weighted'))

Precision -  1.0
Recall -  1.0
F1 score -  1.0

In [306]:
print("Precision - ",precision_score(y_test,lr1.predict(X_test), average='macro'))
print("Recall - ",recall_score(y_test,lr1.predict(X_test), average='macro'))
print("F1 score - ",f1_score(y_test,lr1.predict(X_test), average='macro'))

Precision -  1.0
Recall -  1.0
F1 score -  1.0

In [307]:
from sklearn.metrics import classification_report
print(classification_report(y_test,lr1.predict(X_test) ))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30