<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning/blob/main/32_classification_metrics_binary.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [5]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/MachineLearning/main/heart.csv")

In [6]:
df.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

In [9]:
X=df.drop("target",axis=1)
y=df.iloc[:,-1]

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
lr=LogisticRegression(C=0.1, max_iter=1000)
lr.fit(X_train,y_train)

LogisticRegression(C=0.1, max_iter=1000)

In [18]:
accuracy_score(y_test,lr.predict(X_test))

0.8852459016393442

In [20]:
dt=DecisionTreeClassifier()

In [21]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [22]:
accuracy_score(y_test,dt.predict(X_test))

0.8360655737704918

In [29]:
from pandas.core.frame import DataFrame
print("Decsion tree")
pd.DataFrame(confusion_matrix(y_test,dt.predict(X_test)),columns=list(range(0,2)))

Decsion tree

    0   1
0  27   2
1   8  24

In [30]:
print("Logistic tree")
pd.DataFrame(confusion_matrix(y_test,lr.predict(X_test)),columns=list(range(0,2)))

Logistic tree

    0   1
0  25   4
1   3  29

In [31]:
from sklearn.datasets import load_iris

In [40]:
X1,y1=load_iris(return_X_y=True)
X_train,X_test,y_train,y_test=train_test_split(X1,y1, test_size=0.2, random_state=42)

In [41]:
lr1=LogisticRegression()
lr1.fit(X_train,y_train)
print("Multi  tree")
pd.DataFrame(confusion_matrix(y_test,lr1.predict(X_test)),columns=list(range(0,3)))

Multi  tree

    0  1   2
0  10  0   0
1   0  9   0
2   0  0  11

In [42]:
accuracy_score(y_test,lr1.predict(X_test))

1.0