<a href="https://colab.research.google.com/github/ajaykumar080286/MachineLearning/blob/main/37_Naview_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/ajaykumar080286/MachineLearning/main/PlayTennis.csv")

In [ ]:
df.head(3)

    Outlook Temperature Humidity    Wind Play Tennis
0     Sunny         Hot     High    Weak          No
1     Sunny         Hot     High  Strong          No
2  Overcast         Hot     High    Weak         Yes

In [ ]:
df["Play Tennis"].value_counts()

Play Tennis
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
py=9/14
pn=5/14

In [ ]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [ ]:
pd.crosstab(df["Outlook"],df["Play Tennis"])

Play Tennis  No  Yes
Outlook
Overcast      0    4
Rain          2    3
Sunny         3    2

In [ ]:
pon=0/5
prn=2/5
psn=3/5

poy=4/9
pry=3/9
psy=2/9

In [ ]:
pd.crosstab(df["Temperature"],df["Play Tennis"])

Play Tennis  No  Yes
Temperature
Cool          1    3
Hot           2    2
Mild          2    4

In [ ]:
pcn=1/5
phn=2/5
pmn=2/5

pcy=3/9
phy=2/9
pmy=4/9

In [ ]:
pd.crosstab(df["Humidity"],df["Play Tennis"])

Play Tennis  No  Yes
Humidity
High          4    3
Normal        1    6

In [ ]:
phmn=4/5
pnmn=1/5

phmy=3/9
pnmy=6/9

In [ ]:
pd.crosstab(df["Wind"],df["Play Tennis"])

Play Tennis  No  Yes
Wind
Strong        3    3
Weak          2    6

In [ ]:
psn=3/5
pwn=2/5

psy=3/9
pwy=6/9

In [ ]:
#Outlook=Suunnay, temp=Hot, Humadity=High ,Wind=week if Yes
pynew=py*psy*phy*pnmy*pnmy

pynew

0.021164021164021163

In [ ]:
#Outlook=Suunnay, temp=Hot, Humadity=High ,Wind=week if No
pnnew=pn*psn*phn*pnmn*pnmn

pnnew

0.003428571428571429

In [44]:
#output Play Yes

In [ ]:
#for Numeric data
#use can use gausion, binomail NV, multinomial NV, Possion NV distrubtion